name: stopwatch-python-tests
on: push
jobs:
  linux_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set Python Version
      uses: actions/setup-python@v1
      with: 
        python-version: 3.6
    - name: Check Runtime
      run: python -V
    - name: Check Files
      run: ls
    - name: Install
      run: |
        cd scripts
        ./build.sh
        ./install.sh
    - name: Run Tests
      run: python tests
      
