name: stopwatch-python-tests
on: push
jobs:
  linux_tests:
    runs-on: ubuntu-latest
    steps:
    - &linux_clone name: Clone
      uses: actions/checkout@v1
    - name: Install Runtime
      uses: actions/setup-python@v1
      with: 
        python-version: 3.6
    - name: Check Runtime
      run: python -V
    - name: Install Dependency
      run: |
        pip install setuptools
        pip install wheel
    - name: Install Stopwatch
      run: |
        cd scripts
        chmod +x build.sh
        chmod +x install.sh
        ./build.sh
        ./install.sh
    - name: Run Tests
      run: python tests
  macos_tests:
    runs-on: macOS-latest
    steps:
    - *linux_clone
    - name: Install Runtime
      uses: actions/setup-python@v1
      with: 
        python-version: 3.6
    - name: Check Runtime
      run: python -V
    - name: Install Dependency
      run: |
        pip install setuptools
        pip install wheel
    - name: Install Stopwatch
      run: |
        cd scripts
        chmod +x build.sh
        chmod +x install.sh
        ./build.sh
        ./install.sh
    - name: Run Tests
      run: python tests
  windows_tests:
    runs-on: windows-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1
    - name: Install Runtime
      uses: actions/setup-python@v1
      with: 
        python-version: 3.6
    - name: Check Runtime
      run: python -V
    - name: Install Dependency
      run: |
        pip install setuptools
        pip install wheel
    - name: Install Stopwatch
      run: |
        cd scripts
        ./build.cmd
        ./install.cmd
      shell: pwsh
    - name: Run Tests
      run: python tests
     
